### ISSUE TITLE
Back To Top Button Issue in README file

### ISSUE THREAD

**Issue by MaikolCid** [pasqualerossi/42-Piscine#4]
Hello @pasqualerossi,

you have an issue regarding to the back to top button in the README file. When you click it once, it moves to the top, but after that it doesn't work anymore, cause in the URL there is already ?tab=readme-ov-file#top and even if you refresh your browser it doesn't move to the top.

Regards,
Miguel Cid.

**Comment by pasqualerossi** [comment]
Thanks for letting me know!
